kebs/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include("django.contrib.auth.urls")),
    path('',include("authentication.urls")),
    path('',include("dashboard.urls")),
    path('', include("membership.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

membership/urls.py
from django.urls import path
from membership.views import *

app_name = "membership"
urlpatterns = [
    path("regtype", Registration_type_view, name="regtype"),
    path("membertype", Member_type_view, name="membertype"),
    path("applicant_details", Applicant_details_view, name="applicant_details"),
    path("academic_qualification", Academic_qualification_view, name="academic_qualification"),
    path("specialized_area", Specialized_area_view, name="specialized_area"),
    path("information_on_present_position", Information_on_present_position_view, name="information_on_present_position"),
    path("length_of_tenure", Length_of_tenure_view, name="length_of_tenure"),
    path("courses_related_to_quality_management", Courses_related_to_quality_management_view, name="courses_related_to_quality_management"),
    path("other_management_system_trainings", Other_management_system_trainings_view, name="other_management_system_trainings"),
    path("code_of_conduct", Code_of_conduct_view, name="code_of_conduct"),
    path("statement_of_the_applicant", Statement_of_the_applicant_view, name="statement_of_the_applicant"),
    path("detailed_applicant/<int:user_id>/", Detailed_applicant_view, name="detailed_applicant"),

]

membership/forms.py
from django import forms
from .models import Registration_type,Member_type,Applicant_details,Academic_qualification,Specialized_area,Information_on_present_position,Length_of_tenure,Courses_related_to_quality_management,Other_management_system_trainings,Code_of_conduct, Statement_of_the_applicant

class Registration_type_forms(forms.ModelForm):
        class Meta:
            model = Registration_type
            exclude=('user',)

class Member_type_forms(forms.ModelForm):
       class Meta:
           model = Member_type
           exclude = ('user',)

class Applicant_details_forms(forms.ModelForm):
       class Meta:
           model = Applicant_details
           exclude = ('user',)

class Academic_qualification_forms(forms.ModelForm):
      class Meta:
          model = Academic_qualification
          exclude = ('user',)

class Specialized_area_forms(forms.ModelForm):
      class Meta:
          model = Specialized_area
          exclude = ('user',)

class Information_on_present_position_forms(forms.ModelForm):
      class Meta:
          model = Information_on_present_position
          exclude = ('user',)

class Length_of_tenure_forms(forms.ModelForm):
      class Meta:
          model = Length_of_tenure
          exclude = ('user',)

class Courses_related_to_quality_management_forms(forms.ModelForm):
      class Meta:
          model = Courses_related_to_quality_management
          exclude = ('user',)

class Other_management_system_trainings_forms(forms.ModelForm):
      class Meta:
          model = Other_management_system_trainings
          exclude = ('user',)

class Code_of_conduct_forms(forms.ModelForm):
      class Meta:
          model = Code_of_conduct
          exclude = ('user',)

class Statement_of_the_applicant_forms(forms.ModelForm):
      class Meta:
          model = Statement_of_the_applicant
          exclude = ('user',)


membership/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .forms import Registration_type_forms,Member_type_forms,Applicant_details_forms,Academic_qualification_forms,Specialized_area_forms,Information_on_present_position_forms,Length_of_tenure_forms,Courses_related_to_quality_management_forms,Other_management_system_trainings_forms,Code_of_conduct_forms,Statement_of_the_applicant_forms
from membership.models import Member_type,Registration_type,Applicant_details,Academic_qualification,Specialized_area,Information_on_present_position,Length_of_tenure,Courses_related_to_quality_management,Other_management_system_trainings,Code_of_conduct,Statement_of_the_applicant,Membership_applications
# Create your views here.
@login_required
def Registration_type_view(request):
    try:
        registration_type = Registration_type.objects.get(user=request.user)
        form = Registration_type_forms(request.POST or None, instance=registration_type)

        if request.method == "POST":
            if form.is_valid():
                form.save()
                return redirect("membership:membertype")
        else:
            form = Registration_type_forms(instance=registration_type)

    except Registration_type.DoesNotExist:
        form = Registration_type_forms(request.POST or None)

        if request.method == "POST":
            if form.is_valid():
                member_type = form.save(commit=False)
                member_type.user = request.user
                member_type.save()
                return redirect("membership:membertype")

    return render(request, "regtype.html", {"context": form})
#    form = Registration_type_forms()

#   if request.method == "POST":
#        form = Registration_type_forms(request.POST)

#        if form.is_valid():
#            registration_type = form.save(commit=False)
#            registration_type.user = request.user
#            registration_type.save()
#            return redirect("membership:membertype")

#    return render(request, "regtype.html", {"context": form})
@login_required

def Member_type_view(request):
    try:
        member_type = Member_type.objects.get(user=request.user)
        form = Member_type_forms(request.POST or None, instance=member_type)

        if request.method == "POST":
            if form.is_valid():
                form.save()
                return redirect("membership:applicant_details")
        else:
            form = Member_type_forms(instance=member_type)

    except Member_type.DoesNotExist:
        form = Member_type_forms(request.POST or None)

        if request.method == "POST":
            if form.is_valid():
                member_type = form.save(commit=False)
                member_type.user = request.user
                member_type.save()
                return redirect("membership:applicant_details")

    return render(request, "membertype.html", {"context": form})

# @login_required
# def Member_type_view(request):
#     form = Member_type_forms()
#
#     if request.method == "POST":
#       form = Member_type_forms(request.POST)
#
#         if form.is_valid():
#             member_type = form.save(commit=False)
#             member_type.user = request.user
#             member_type.save()
#            return redirect("membership:applicant details")
#
#    return render(request,"membertype.html",{"context":form})

@login_required
def Applicant_details_view(request):
    initial_data = {
        "first_name": request.session['firstname'],
        "last_name": request.session['lastname'],
        "email": request.session['email']

    }
    form = Applicant_details_forms(request.POST or None, initial=initial_data)

    try:
        applicant_details = Applicant_details.objects.get(user=request.user)
        form = Applicant_details_forms(request.POST or None, instance=applicant_details, initial=initial_data)

        if request.method == "POST":
            if form.is_valid():
                form.save()
                return redirect("membership:academic_qualification")
        else:
            form = Applicant_details_forms(instance=applicant_details, initial=initial_data)

    except Applicant_details.DoesNotExist:
        form = Applicant_details_forms(request.POST or None)

        if request.method == "POST":
            if form.is_valid():
                member_type = form.save(commit=False)
                member_type.user = request.user
                member_type.save()
                return redirect("membership:academic_qualification")

    return render(request, "applicant_details.html", {"context": form})



#    if request.method == "POST":
#        form = Applicant_details_forms(request.POST)

#       if form.is_valid():
#            applicant_details = form.save(commit=False)
#            applicant_details.user = request.user
#            applicant_details.save()
#           return redirect("membership:academic qualification")
#    #import pdb;pdb.set_trace()
#    return render(request,"applicant_details.html",{"context":form})

@login_required
def Academic_qualification_view(request):
    try:
        academic_qualification = Academic_qualification.objects.get(user=request.user)
        form = Academic_qualification_forms(request.POST, request.FILES, instance=academic_qualification)

        if request.method == "POST":
            if form.is_valid():
                form.save()
                return redirect("membership:specialized_area")
        else:
            form = Academic_qualification_forms(instance=academic_qualification)

    except Academic_qualification.DoesNotExist:
        form = Academic_qualification_forms(request.POST, request.FILES)

        if request.method == "POST":
            if form.is_valid():
                academic_qualification = form.save(commit=False)
                academic_qualification.user = request.user
                academic_qualification.save()
                return redirect("membership:specialized_area")

    return render(request, "academic_qualification.html", {"context": form})
#    form = Academic_qualification_forms()

#    if request.method == "POST":
#        form = Academic_qualification_forms(request.POST, request.FILES)

#        if form.is_valid():
#            academic_qualification = form.save(commit=False)
#            academic_qualification.user = request.user
#            academic_qualification.save()
#            return redirect("membership:specialized area")

#    return render(request,"academic_qualification.html",{"context":form})
@login_required
def Specialized_area_view(request):
    try:
        specialized_area = Specialized_area.objects.get(user=request.user)
        form = Specialized_area_forms(request.POST or None, instance=specialized_area)

        if request.method == "POST":
            if form.is_valid():
                form.save()
                return redirect("membership:information_on_present_position")
        else:
            form = Specialized_area_forms(instance=specialized_area)

    except Specialized_area.DoesNotExist:
        form = Specialized_area_forms(request.POST or None)

        if request.method == "POST":
            if form.is_valid():
                specialized_area = form.save(commit=False)
                specialized_area.user = request.user
                specialized_area.save()
                return redirect("membership:information_on_present_position")

    return render(request, "specialized_area.html", {"context": form})
#    form = Specialized_area_forms()

#    if request.method == "POST":
#        form = Specialized_area_forms(request.POST)

#        if form.is_valid():
#            specialized_area = form.save(commit=False)
#            specialized_area.user = request.user
#            specialized_area.save()
#           return redirect("membership:information on present position")


#    return render(request,"specialized_area.html",{"context":form})
@login_required
def Information_on_present_position_view(request):
    try:
        information_on_present_position = Information_on_present_position.objects.get(user=request.user)
        form = Information_on_present_position_forms(request.POST or None, instance=information_on_present_position)

        if request.method == "POST":
            if form.is_valid():
                form.save()
                return redirect("membership:length_of_tenure")
        else:
            form = Information_on_present_position_forms(instance=information_on_present_position)

    except Information_on_present_position.DoesNotExist:
        form = Information_on_present_position_forms(request.POST or None)

        if request.method == "POST":
            if form.is_valid():
                information_on_present_position = form.save(commit=False)
                information_on_present_position.user = request.user
                information_on_present_position.save()
                return redirect("membership:length_of_tenure")

    return render(request, "information_on_present_position.html", {"context": form})
#    form = Information_on_present_position_forms()

#    if request.method == "POST":
#        form = Information_on_present_position_forms(request.POST)

#        if form.is_valid():
#            information_on_present_position = form.save(commit=False)
#            information_on_present_position.user = request.user
#            information_on_present_position.save()
#            return redirect("membership:length of tenure")


#    return render(request,"information_on_present_position.html",{"context":form})
@login_required
def Length_of_tenure_view(request):
    try:
        length_of_tenure = Length_of_tenure.objects.get(user=request.user)
        form = Length_of_tenure_forms(request.POST or None, instance=length_of_tenure)

        if request.method == "POST":
            if form.is_valid():
                form.save()

membership/templates/academic_qualification.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
 <style>
            .button-container {
                display: flex;
                justify-content: space-between;
                margin-top: 20px;
            }

            .button-container .previous-button {
                order: 1;
            }

            .button-container .next-button {
                order: 2;
            }

    </style>
<main id="main" class="main">
    <div class="container">
    <h3> Academic Qualifications: </h3>
        <form method="POST" action="{% url 'membership:academic_qualification' %}" enctype="multipart/form-data">
            {% csrf_token %}
    <div class="row">
        <div class="col-12">
            {{ context.name_of_institution|as_crispy_field }}
        </div>

        <div class="row">
            <div class="col-6">
                {{ context.date_from|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ context.date_to|as_crispy_field }}
            </div>
        </div>

        <div class="row">
            <div class="col-4">
                {{ context.course_duration_in_years|as_crispy_field }}
            </div>
        </div>

        <div class="row">
            <div class="col-6">
                 {{ context.certificate_awarded|as_crispy_field }}
            </div>
                <div class="col-6">
                {{ context.certificate_file|as_crispy_field }}
                </div>
            </div>
        <div class="button-container">
        <a href="{% url 'membership:applicant_details' %}" class="btn btn-primary previous-button">Previous</a>
            <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />

    </div>


        </div>
        </form>
    </div>
</main>
{% endblock %}

membership/templates/applicant_details.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
            .button-container {
                display: flex;
                justify-content: space-between;
                margin-top: 20px;
            }

            .button-container .previous-button {
                order: 1;
            }

            .button-container .next-button {
                order: 2;
            }

    </style>
<main id="main" class="main">
<div class="container">
    <h3> Applicant Details </h3>
    <form method="POST" action="{% url 'membership:applicant_details' %}">
            {% csrf_token %}
    <div class="row">
        <div class="col-3">
            {{ context.tittle|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            {{ context.first_name|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ context.last_name|as_crispy_field }}
        </div>
    </div>

    <div class="row">
        <div class="col-6">
             {{ context.identification_card|as_crispy_field }}
        </div>
        <div class="col-6">
             {{ context.mobile|as_crispy_field }}
        </div>
    </div>

    <div class="row">
        <div class="col-6">
              {{ context.email|as_crispy_field }}
        </div>
        <div class="col-6">
             {{ context.profession|as_crispy_field }}
        </div>
    </div>

    <div class="row">
        <div class="col-6">
             {{ context.organization_name|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ context.organization_telephone|as_crispy_field }}
        </div>
    </div>

    <div class="row">
        <div class="col-8">
             {{ context.organization_address|as_crispy_field }}
        </div>
    </div>

    <div class="row">
        <div class="col-6">
             {{ context.business_email|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ context.nature_of_organization|as_crispy_field }}
        </div>
    </div>
    <div class="button-container">
        <a href="{% url 'membership:membertype' %}" class="btn btn-primary previous-button">Previous</a>
        <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />

    </div>
    </form>


</div>
</main>
{% endblock %}

membership/templates/code_of_conduct.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
            .button-container {
                display: flex;
                justify-content: space-between;
                margin-top: 20px;
            }

            .button-container .previous-button {
                order: 1;
            }

            .button-container .next-button {
                order: 2;
            }

</style>
<main id="main" class="main">
    <h3> Code of Conduct</h3>
    <div class="container">
        <form method="POST" action="{% url 'membership:code_of_conduct' %}">
            {% csrf_token %}
{{ context|crispy }}
    </div>
    <div class="button-container">
        <a href="{% url 'membership:other_management_system_trainings' %}" class="btn btn-primary  previous-button">Previous</a>
        <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />
    </div>
    </form>

</main>
{% endblock %}

membership/templates/confirmation.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<main id="main" class="main">
    <h3> Confirmation </h3>
    <div class="container">

 <h1>Application Confirmation</h1>
  <p>Dear {{ applicant_name }},</p>
  <p>Thank you for submitting your application form. We have received your information and appreciate your interest in [Company/Organization Name]. Our team is currently reviewing your application, and we will be in touch shortly with any further steps in the process.</p>
  <p>If you have any additional questions or need further information, please feel free to reach out to us. We appreciate your patience and look forward to the possibility of working together.</p>
  <p>Best regards,</p>
  <p>{{ your_name }}</p>
  <p>[Company/Organization Name]</p>
    </div>
</main>

{% endblock %}

membership/templates/courses_related_to_quality_management.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
            .button-container {
                display: flex;
                justify-content: space-between;
                margin-top: 20px;
            }

            .button-container .previous-button {
                order: 1;
            }

            .button-container .next-button {
                order: 2;
            }

</style>
<main id="main" class="main">
    <h3> Courses/Training related to quality management </h3>
     <form method="POST" action="{% url 'membership:courses_related_to_quality_management' %}" enctype="multipart/form-data">
            {% csrf_token %}
    <div class="container">
        <div class="row">
            {{ context.Course|as_crispy_field }}
        </div>
        <div class="row">
            {{ context.Course_duration_in_years|as_crispy_field }}
        </div>
        <div class="row">
            {{ context.Organization|as_crispy_field }}
        </div>
        <div class="row">
            <div class="col-6">
                {{ context.Certificate_awarded|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ context.certificate_file|as_crispy_field }}
            </div>
        </div>
    </div>
    <div class="button-container">
        <a href="{% url 'membership:length_of_tenure' %}" class="btn btn-primary previous-button">Previous</a>
         <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />
    </div>
     </form>

</main>
{% endblock %}

membership/templates/information_on_present_position.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
            .button-container {
                display: flex;
                justify-content: space-between;
                margin-top: 20px;
            }

            .button-container .previous-button {
                order: 1;
            }

            .button-container .next-button {
                order: 2;
            }

</style>

<main id="main" class="main">
    <div class="container">
    <h3> Please give a brief description on current Quality-related responsibilities(indicate if there are additional responsibilities since initial application)</h3>
        <form method="POST" action="{% url 'membership:information_on_present_position' %}">
            {% csrf_token %}
    <div class="row">
        {{ context.description_on_current_quality|as_crispy_field }}
    </div>

    <div class="row">
        {{ context.any_other_specify|as_crispy_field }}
    </div>
    <h4> Length of tenure on present position</h4>
    <div class="row">
        <div class="col-6">
            {{ context.years|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ context.months|as_crispy_field }}
        </div>
    </div>
    </div>
    <div class="button-container">
        <a href="{% url 'membership:specialized_area' %}" class="btn btn-primary previous-button">Previous</a>
        <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />

    </div>

    </form>

</main>
{% endblock %}

membership/templates/length_of_tenure.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
            .button-container {
                display: flex;
                justify-content: space-between;
                margin-top: 20px;
            }

            .button-container .previous-button {
                order: 1;
            }

            .button-container .next-button {
                order: 2;
            }

</style>
<main id="main" class="main">
    <h3> Length of Tenure </h3>
    <div class="container">
        <form method="POST" action="{% url 'membership:length_of_tenure' %}">
            {% csrf_token %}
 <div class="row">
     {{ context.Name_of_organization|as_crispy_field }}
 </div>

    <div class="row">
        <div class="col-6">
            {{ context.date_from|as_crispy_field }}
        </div>
        <div class="col-6">
            {{ context.date_to|as_crispy_field }}
        </div>
    </div>
    </div>
    <div class="button-container">
        <a href="{% url 'membership:information_on_present_position' %}" class="btn btn-primary previous-button">Previous</a>
        <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />
    </div>
    </form>

</main>
{% endblock %}

membership/templates/membertype.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
            .button-container {
                display: flex;
                justify-content: space-between;
                margin-top: 20px;
            }

            .button-container .previous-button {
                order: 1;
            }

            .button-container .next-button {
                order: 2;
            }

    </style>
<main id="main" class="main">
    <h3> Member type </h3>
    <div class="container">
         <form method="POST" action="{% url 'membership:membertype' %}">
            {% csrf_token %}
{{ context|crispy }}
    </div>
    <div class="button-container">
        <a href="{% url 'membership:regtype' %}" class="btn btn-primary previous-button">Previous</a>
        <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />
    </div>

         </form>

</main>
{% endblock %}

membership/templates/other_management_system_trainings.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
 <style>
            .button-container {
                display: flex;
                justify-content: space-between;
                margin-top: 20px;
            }

            .button-container .previous-button {
                order: 1;
            }

            .button-container .next-button {
                order: 2;
            }

</style>
<main id="main" class="main">
    <h3> Other management system trainings</h3>
    <form method="POST" action="{% url 'membership:other_management_system_trainings' %}" enctype="multipart/form-data">
            {% csrf_token %}
    <div class="container">
        <div class="row">
            {{ context.Course|as_crispy_field }}
        </div>
        <div class="row">
            {{ context.Course_duration_in_years|as_crispy_field }}
        </div>
        <div class="row">
            {{ context.Organization|as_crispy_field }}
        </div>
        <div class="row">
            <div class="col-6">
                {{ context.Certificate_awarded|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ context.certificate_file|as_crispy_field }}
            </div>
        </div>
    </div>
    <div class="button-container">
        <a href="{% url 'membership:courses_related_to_quality_management' %}" class="btn btn-primary  previous-button">Previous</a>
        <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />
    </div>
    </form>
</main>
{% endblock %}

membership/templates/regtype.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
            .button-container {
                display: bottom-right;
                justify-content: space-between;
                margin-top: 20px;


</style>
<main id="main" class="main">
    <h3> Type of registration </h3>
    <div class="container">
        <form method="post" action="{% url 'membership:regtype' %}">
            {% csrf_token %}
    {{ context|crispy }}
    </div>
<div class="button-container">

    <input type="submit" name="submit" value="next" class="btn btn-primary" />

       </div>
    </form>

</main>

{% endblock %}

membership/templates/specialized_area.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
            .button-container {
                display: flex;
                justify-content: space-between;
                margin-top: 20px;
            }

            .button-container .previous-button {
                order: 1;
            }

            .button-container .next-button {
                order: 2;
            }

</style>
<main id="main" class="main">
    <div class="container">
    <h3>Areas of specialization that best reflects your activities in quality related field</h3>
        <form method="POST" action="{% url 'membership:specialized_area' %}">
            {% csrf_token %}
{{ context|crispy }}
    </div>
    <div class="button-container">
        <a href="{% url 'membership:academic_qualification' %}" class="btn btn-primary previous-button">Previous</a>
        <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />
    </div>
        </form>

</main>
{% endblock %}

membership/templates/statement_of_the_applicant.html
{% extends 'base2.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<main id="main" class="main">
    <h3> Statement of the applicant </h3>
     <form method="POST" action="{% url 'membership:statement_of_the_applicant' %}">
            {% csrf_token %}
    <div class="container">
{{ context|crispy }}
    </div>
         <input type="submit" name="submit" value="next"   class="btn btn-primary next-button" Next />
     </form>
</main>
{% endblock %}