dashboard/urls.py
from django.urls import path
from dashboard.views import Dashboard_view

app_name = "dashboard"
urlpatterns = [
    path('dashboard/',Dashboard_view, name='dashboard'),
    path('dashboard/',Dashboard_view, name='membershipofficer dashboard'),
    path('dashboard/',Dashboard_view, name='detailed_applicant')
    #path("Dashboard",Dashboard, name="Dashboard"),
]

kebs/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include("django.contrib.auth.urls")),
    path('',include("authentication.urls")),
    path('',include("dashboard.urls")),
    path('', include("membership.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

membership/urls.py
from django.urls import path
from membership.views import *

app_name = "membership"
urlpatterns = [
    path("regtype", Registration_type_view, name="regtype"),
    path("membertype", Member_type_view, name="membertype"),
    path("applicant_details", Applicant_details_view, name="applicant_details"),
    path("academic_qualification", Academic_qualification_view, name="academic_qualification"),
    path("specialized_area", Specialized_area_view, name="specialized_area"),
    path("information_on_present_position", Information_on_present_position_view, name="information_on_present_position"),
    path("length_of_tenure", Length_of_tenure_view, name="length_of_tenure"),
    path("courses_related_to_quality_management", Courses_related_to_quality_management_view, name="courses_related_to_quality_management"),
    path("other_management_system_trainings", Other_management_system_trainings_view, name="other_management_system_trainings"),
    path("code_of_conduct", Code_of_conduct_view, name="code_of_conduct"),
    path("statement_of_the_applicant", Statement_of_the_applicant_view, name="statement_of_the_applicant"),
    path("detailed_applicant/<int:user_id>/", Detailed_applicant_view, name="detailed_applicant"),

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render,redirect
from membership.models import Membership_applications

# Create your views here.
def Dashboard_view(request):
    user = request.user
    if user.groups.filter(name='client').exists():
        return render(request, "dashboard.html")
    elif user.groups.filter(name='membership_officer').exists():
        completed_applications = []

        for member in Membership_applications.objects.all():
            user_id = member.Member.id
            first_name = member.Member.first_name
            last_name = member.Member.last_name
            email = member.Member.email

            completed_applications.append({"user_id":user_id, "first_name":first_name, "last_name":last_name, "email":email})

        #completed_applications = Membership_applications.objects.all().values()
        # import pdb;pdb.set_trace()
        return render(request, "membershipofficer dashboard.html", {"data": completed_applications})
    #Dashboard(request)
    #return render(request,"dashboard.html")

dashboard/templates/dashboard.html
{% extends 'base2.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<main id="main" class="main">


    <div class="pagetitle">
      <h1>Dashboard</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">

        <!-- Left side columns -->
        <div class="col-lg-8">
          <div class="row">

            <!-- Sales Card -->
            <div class="col-xxl-4 col-md-6">
              <div class="card info-card sales-card">



                <div class="card-body">
                  <h5 class="card-title">Application </h5>

                  <div class="d-flex align-items-center">
                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                     
                    </div>

                  </div>
                </div>

              </div>
            </div><!-- End Sales Card -->

            <!-- Revenue Card -->
            <div class="col-xxl-4 col-md-6">
              <div class="card info-card revenue-card">



                <div class="card-body">
                  <h5 class="card-title">Member Type </h5>
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <div class="d-flex align-items-center">

                    </div>
                    <div class="ps-3">



                    </div>
                  </div>
                </div>

              </div>
            </div><!-- End Revenue Card -->
             <div class="col-xxl-4 col-md-6">
              <div class="card info-card revenue-card">



                <div class="card-body">
                  <h5 class="card-title">Membership Status </h5>
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <div class="d-flex align-items-center">

                    </div>
                    <div class="ps-3">



                    </div>
                  </div>
                </div>

              </div>
            </div><!-- End Revenue Card -->
            <div class="col-xxl-4 col-md-6">
              <div class="card info-card revenue-card">



                <div class="card-body">
                  <h5 class="card-title">My invoices </h5>

                  <div class="d-flex align-items-center">

                    </div>
                    <div class="ps-3">



                    </div>
                  </div>
                </div>

              </div>
            </div><!-- End Revenue Card -->

            <!-- Reports -->
            <div class="col-12">
              <div class="card">



                <div class="card-body">
                  <h5 class="card-title">My Application </h5>
                   <a class="button" href="{% url 'membership:regtype' %}">Continue Application</a>
                   <style>
                       .button {
                            display: inline-block;
                            position: absolute;
                            top: 10px;
                            right: 10px;
                            padding: 10px 20px;
                            background-color: #4CAF50;
                            color: white;
                            text-decoration: none;
                            border-radius: 4px;
                            transition: background-color 0.3s ease;
                          }

                  .button:hover {
                    background-color: #45a049;
                            th {
                              padding: 10px; /* Adjust the value as needed */
                            }
                            tr {
                              margin-bottom: 10px;
                   </style>
                  <div>
                   <table>
                    <thead>
                      <tr>
                        <th>No</th>
                        <th>Type</th>
                        <th>Membership No</th>
                        <th>Status</th>
                        <th>Action</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td></td>
                        <td></td>
                        <td> </td>
                        <td> </td>
                        <td></td>
                      </tr>

                      <!-- Add more rows as needed -->
                    </tbody>
                  </table>
                    </div>
                  <!-- Line Chart -->
                  <div id="reportsChart"></div>

                  <!-- End Line Chart -->

                </div>

              </div>
            </div><!-- End Reports -->

            <!-- Recent Sales -->

            <!-- Top Selling -->


          </div>
        </div><!-- End Left side columns -->


    </section>

  </main><!-- End #main -->
{% endblock %}

dashboard/templates/membershipofficer dashboard.html
{% extends 'base2.html' %}
{% load static %}
{% block title %}Login{% endblock %}
{% block content %}
<style>
    /* Style the tab buttons */
    .tab {
        overflow: hidden;
    }

    .tab button {
        background-color: #f1f1f1;
        float: left;
        border: 1px solid #ccc;
        outline: none;
        cursor: pointer;
        padding: 8px 16px;
        transition: 0.3s;
    }

    .tab button:hover {
        background-color: #ddd;
    }

    /* Style the tab content */
    .tabcontent {
        display: none;
        padding: 20px;
        border: 1px solid #ccc;
    }
</style>
<main id="main" class="main">


    <div class="pagetitle">
      <h1>Dashboard</h1>
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="index.html">Home</a></li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
    </div><!-- End Page Title -->

    <section class="section dashboard">
      <div class="row">
        <!-- Left side columns -->

          <div class="row">
            <!-- Sales Card -->
            <div class="col-4">
              <div class="card info-card sales-card">
                <div class="card-body">
                  <h5 class="card-title">All </h5>
                  <div class="d-flex align-items-center">
                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                    </div>
                  </div>
                </div>
              </div>
            </div><!-- End Sales Card -->
            <!-- Revenue Card -->
            <div class="col-4">
              <div class="card info-card revenue-card">
                <div class="card-body">
                  <h5 class="card-title">Approved</h5>
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <div class="d-flex align-items-center">
                  </div>
                    <div class="ps-3">
                    </div>
                  </div>
                </div>
              </div>
            </div><!-- End Revenue Card -->
             <div class="col-4">
              <div class="card info-card revenue-card">
                <div class="card-body">
                  <h5 class="card-title">Rejected </h5>
                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                  <div class="d-flex align-items-center">
                  </div>
                    <div class="ps-3">
                    </div>
                  </div>
                </div>
              </div>
            </div><!-- End Revenue Card -->

                  <div class="d-flex align-items-center">

                    </div>
                    <div class="ps-3">



                    </div>
                  </div>
                </div>

              </div>
            </div><!-- End Revenue Card -->

            <!-- Reports -->
            <div class="col-12">
              <div class="card">





                  <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <h5 class="card-title">Datatables</h5>
              <p>Add lightweight datatables to your project with using the <a href="https://github.com/fiduswriter/Simple-DataTables" target="_blank">Simple DataTables</a> library. Just add <code>.datatable</code> class name to any table you wish to conver to a datatable</p>

              <!-- Table with stripped rows -->
              <table class="table datatable">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">first_name</th>
                    <th scope="col">last_name</th>
                    <th scope="col">email</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for applicant in data %}

                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ applicant.first_name }}</td>
                    <td>{{ applicant.last_name }}</td>
                    <td>{{ applicant.email }}</td>
                    <td>
                       <a href="{% url  'membership:detailed_applicant' applicant.user_id %}" class="btn btn-primary view-btn" data-user-id="">Views</a>
                      <!-- Actions for the applicant (if any) --></td>
                  </tr>
                  {% endfor %}

                  </tbody>
                  </table>
              <!-- End Table with stripped rows -->
              <!-- Tab container -->
                </div>
              </div>
            </div>
          </div>
             
                   <!-- Tab content -->





          </div>
              </div>
             </div>

             </div>
               </div>
         </section>





                  </div>
                  <!-- Line Chart -->
                  <div id="reportsChart"></div>

                  <!-- End Line Chart -->

                </div>

              </div>
            </div><!-- End Reports -->

            <!-- Recent Sales -->

            <!-- Top Selling -->


          </div>
        </div><!-- End Left side columns -->


    </section>

  </main><!-- End #main -->
{% endblock %}